language: elixir
sudo: false

elixir:
  - 1.7
otp_release:
  - 21.1

script:
  - make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  recipients:
    - engineers@straw-hat-llc.com
